using D2MapApi.Common.Enumerations.GameData;

namespace D2MapApi.Common.Enumerations.Extensions;

internal static class D2ObjectExtensions
{
    internal static bool ObjectIsDoor(this D2Object p_object)
    {
        return p_object switch
               {
                   D2Object.DOOR_GATE_LEFT or
                   D2Object.DOOR_GATE_RIGHT or
                   D2Object.DOOR_WOODEN_LEFT or
                   D2Object.DOOR_WOODEN_RIGHT or
                   D2Object.DOOR_COURTYARD_LEFT or
                   D2Object.DOOR_COURTYARD_RIGHT or
                   D2Object.DOOR_CATHEDRAL_DOUBLE or
                   D2Object.DOOR_MONASTERY_DOUBLE_RIGHT or
                   D2Object.ANDARIEL_DOOR or
                   D2Object.DOOR_CATHEDRAL_LEFT or
                   D2Object.DOOR_CATHEDRAL_RIGHT or
                   D2Object.DOOR_WOODEN_LEFT_2 or
                   D2Object.TRAPP_DOOR or
                   D2Object.DOOR_BY_ACT_2_DOCK or
                   D2Object.TOMB_DOOR_LEFT or
                   D2Object.TOMB_DOOR_RIGHT or
                   D2Object.TOMB_DOOR_LEFT_2 or
                   D2Object.TOMB_DOOR_RIGHT_2 or
                   D2Object.SECRET_DOOR_1 or
                   D2Object.TYRAELS_DOOR or
                   D2Object.SLIME_DOOR_1 or
                   D2Object.SLIME_DOOR_2 or
                   D2Object.IRON_GRATE_DOOR_LEFT or
                   D2Object.IRON_GRATE_DOOR_RIGHT or
                   D2Object.WOODEN_GRATE_DOOR_LEFT or
                   D2Object.WOODEN_GRATE_DOOR_RIGHT or
                   D2Object.WOODEN_DOOR_LEFT or
                   D2Object.WOODEN_DOOR_RIGHT or
                   D2Object.TELEPORTATION_PAD_2 or
                   D2Object.TELEPORTATION_PAD_3 or
                   D2Object.TELEPORTATION_PAD_4 or
                   D2Object.DUMMY_ARCANE_THING_1 or
                   D2Object.DUMMY_ARCANE_THING_2 or
                   D2Object.DUMMY_ARCANE_THING_3 or
                   D2Object.DUMMY_ARCANE_THING_4 or
                   D2Object.DUMMY_ARCANE_THING_5 or
                   D2Object.DUMMY_ARCANE_THING_6 or
                   D2Object.DUMMY_ARCANE_THING_7 or
                   D2Object.ACT_3_SEWER_STAIRS or
                   D2Object.ACT_3_SEWER_STAIRS_TO_LEVEL_3 or
                   D2Object.EXPANSION_TOWN_GATE or
                   D2Object.SIEGE_HELL_GATE or
                   D2Object.PEN_BREAKABLE_DOOR or
                   D2Object.ARREAT_SUMMIT_DOOR_TO_WORLDSTONE or
                   D2Object.ARREAT_SUMMIT_DOOR or
                   D2Object.DOOR_BLOCKER_1 or
                   D2Object.DOOR_BLOCKER_2 => true,
                   _ => false
               };
    }

    internal static bool ObjectIsNotInteractive(this D2Object p_object)
    {
        return p_object switch
               {
                   D2Object.HELL_LAVA_2 or
                   D2Object.ACT_2_BRAZIER_TALL or
                   D2Object.ACT_2_BRAZIER_SMALL or
                   D2Object.MEPHISTO_BRIDGE or
                   D2Object.HRATLI_END_POSITION or
                   D2Object.HRATLI_START_POSITION or
                   D2Object.HELL_MESA_BRAZIER or
                   D2Object.STAIRS_R or
                   D2Object.CAIN_START_POSITION or
                   D2Object.NATALYA_START_POSITION or
                   D2Object.HELL_SKELETON_SPAWN_NE or
                   D2Object.HELL_BRAZIER_2 or
                   D2Object.HELL_BRAZIER_1 or
                   D2Object.HELL_LIGHT_SOURCE_1 or
                   D2Object.HELL_LIGHT_SOURCE_2 or
                   D2Object.HELL_LIGHT_SOURCE_3 or
                   D2Object.SMOKE or
                   D2Object.HELL_BRAZIER_3 or
                   D2Object.SIEGE_MACHINE_CONTROL or
                   D2Object.DREHYA_TOWN_START_POSITION or
                   D2Object.DREHYA_WILDERNESS_START_POSITION or
                   D2Object.NIHLATHAK_TOWN_START_POSITION or
                   D2Object.NIHLATHAK_WILDERNESS_START_POSITION or
                   D2Object.LARZUK_STANDARD or
                   D2Object.LARZUK_GREETING or
                   D2Object.ACT_2_BRAZIER or
                   D2Object.ACT_2_BRAZIER_CELLER or
                   D2Object.ACT_3_WATER_FOG or
                   D2Object.TEST_DATA_1 or
                   D2Object.LARGE_URN_1 or
                   D2Object.BARREL or
                   D2Object.TOWER_TOME or
                   D2Object.URN_2 or
                   D2Object.BENCH or
                   D2Object.BARREL_EXPLODING or
                   D2Object.ROGUE_FOUNTAIN or
                   D2Object.CAIN_GIBBET or
                   D2Object.HOLE_ANIM or
                   D2Object.BRAZIER or
                   D2Object.FOUNTAIN or
                   D2Object.CRUCIFIX or
                   D2Object.CANDLES_1 or
                   D2Object.CANDLES_2 or
                   D2Object.STANDARD_1 or
                   D2Object.STANDARD_2 or
                   D2Object.TORCH_1_TIKI or
                   D2Object.TORCH_2_WALL or
                   D2Object.ROGUE_BONFIRE or
                   D2Object.RIVER_1 or
                   D2Object.RIVER_2 or
                   D2Object.RIVER_3 or
                   D2Object.RIVER_4 or
                   D2Object.RIVER_5 or
                   D2Object.AMBIENT_SOUND_GENERATOR or
                   D2Object.CRATE or
                   D2Object.ROGUE_TORCH_1 or
                   D2Object.ROGUE_TORCH_2 or
                   D2Object.URN_3 or
                   D2Object.ROGUE_CORPSE_ROLLING or
                   D2Object.CORPSE_ON_STICK_1 or
                   D2Object.CORPSE_ON_STICK_2 or
                   D2Object.INVISIBLE_OBJECT or
                   D2Object.INVISIBLE_RIVER_SOUND_1 or
                   D2Object.INVISIBLE_RIVER_SOUND_2 or
                   D2Object.RIPPLE_1 or
                   D2Object.RIPPLE_2 or
                   D2Object.RIPPLE_3 or
                   D2Object.RIPPLE_4 or
                   D2Object.FOREST_NIGHT_SOUND_1 or
                   D2Object.FOREST_NIGHT_SOUND_2 or
                   D2Object.YETI_DUNG or
                   D2Object.SEWER_DRIP or
                   D2Object.HEALTH_ORAMA or
                   D2Object.INVISIBLE_TOWN_SOUND or
                   D2Object.OBELISK or
                   D2Object.BUBBLING_POOL_OF_BLOOD or
                   D2Object.LARGE_URN_4 or
                   D2Object.LARGE_URN_5 or
                   D2Object.BRAZIER_3 or
                   D2Object.FLOOR_BRAZIER or
                   D2Object.FLIES or
                   D2Object.MALUS or
                   D2Object.DRINKER or
                   D2Object.GESTURER or
                   D2Object.JUNGLE_TORCH or
                   D2Object.JERHYN_PLACE_HOLDER_1 or
                   D2Object.JERHYN_PLACE_HOLDER_2 or
                   D2Object.VILE_DOG_AFTERGLOW or
                   D2Object.DESERT_JUG_1 or
                   D2Object.DESERT_JUG_2 or
                   D2Object.GUARD_CORPSE or
                   D2Object.HIDDEN_STASH_ROCK or
                   D2Object.SKELETON_CORPSE_IS_AN_OXYMORON or
                   D2Object.HIDDEN_STASH_ROCK_B or
                   D2Object.SMALL_FIRE or
                   D2Object.MEDIUM_FIRE or
                   D2Object.LARGE_FIRE or
                   D2Object.ACT_1_CLIFF_HIDING_SPOT or
                   D2Object.HOLLOW_LOG or
                   D2Object.SKELETON_CORPSE_IS_STILL_AN_OXYMORON or
                   D2Object.LOOSE_ROCK or
                   D2Object.LOOSE_BOULDER or
                   D2Object.GUARD_CORPSE_ON_A_STICK or
                   D2Object.BOOKSHELF_1 or
                   D2Object.BOOKSHELF_2 or
                   D2Object.TOMB_COFFIN or
                   D2Object.JUNGLE_STASH_OBJECT_1 or
                   D2Object.JUNGLE_STASH_OBJECT_2 or
                   D2Object.JUNGLE_STASH_OBJECT_3 or
                   D2Object.JUNGLE_STASH_OBJECT_4 or
                   D2Object.DUMMY_CAIN_PORTAL or
                   D2Object.TELEPORTATION_PAD_1 or
                   D2Object.STAIRS_L or
                   D2Object.STAIRS_R or
                   D2Object.FLOOR_TRAP or
                   D2Object.STASH_BOX or
                   D2Object.STASH_ALTAR or
                   D2Object.ACT_3_WATER_ROCKS or
                   D2Object.BASKET_1 or
                   D2Object.BASKET_2 or
                   D2Object.ACT_3_WATER_LOGS or
                   D2Object.ACT_3_WATER_ROCKS_GIRL or
                   D2Object.ACT_3_WATER_BUBBLES or
                   D2Object.ACT_3_WATER_LOGS_X or
                   D2Object.ACT_3_WATER_ROCKS_B or
                   D2Object.ACT_3_WATER_ROCKS_GIRL_C or
                   D2Object.ACT_3_WATER_ROCKS_Y or
                   D2Object.ACT_3_WATER_LOGS_Z or
                   D2Object.WEB_COVERED_TREE_1 or
                   D2Object.WEB_COVERED_TREE_2 or
                   D2Object.WEB_COVERED_TREE_3 or
                   D2Object.WEB_COVERED_TREE_4 or
                   D2Object.PILLAR or
                   D2Object.COCOON or
                   D2Object.COCOON_2 or
                   D2Object.SKULL_PILE_H_1 or
                   D2Object.ACT_3_WATER_ROCKS_GIRL_W or
                   D2Object.ACT_3_BIG_LOG or
                   D2Object.PILLAR_H_2 or
                   D2Object.ACT_3_BIG_LOG_C or
                   D2Object.ACT_3_BIG_LOG_D or
                   D2Object.BURNING_BODY_TOWN or
                   D2Object.SEWERS_RAT_NEST or
                   D2Object.BURNING_BODY_TOWN_2 or
                   D2Object.SEWERS_RAT_NEST_2 or
                   D2Object.ACT_1_BED_BED_1 or
                   D2Object.ACT_1_BED_BED_2 or
                   D2Object.EXPLODING_COW or
                   D2Object.GIDBINN_ALTAR_DECOY or
                   D2Object.DIABLO_RIGHT_LIGHT or
                   D2Object.DIABLO_LEFT_LIGHT or
                   D2Object.DIABLO_START_POINT or
                   D2Object.ACT_1_CABIN_STOOL or
                   D2Object.ACT_1_CABIN_WOOD or
                   D2Object.ACT_1_CABIN_WOOD_2 or
                   D2Object.HELL_SKELETON_SPAWN_NW or
                   D2Object.TOMBS_FLOOR_TRAP_SPIKES or
                   D2Object.MAGGOT_LAIR_GOO_PILE or
                   D2Object.BANK or
                   D2Object.GOLD_PLACE_HOLDER or
                   D2Object.GUARD_CORPSE_2 or
                   D2Object.TOMBS_WALL_TORCH_LEFT or
                   D2Object.TOMBS_WALL_TORCH_RIGHT or
                   D2Object.ACT_3_SEWER_TORCH or
                   D2Object.ACT_3_KURAST_TORCH or
                   D2Object.HELL_FIRE_1 or
                   D2Object.HELL_FIRE_2 or
                   D2Object.HELL_FIRE_3 or
                   D2Object.ACT_3_TOWN_TORCH or
                   D2Object.POT_O_TORCH or
                   D2Object.PYOX_FIRE_PIT or
                   D2Object.EXPANSION_WILDERNESS_BARREL or
                   D2Object.EXPANSION_SIEGE_BARREL or
                   D2Object.EXPANSION_TORCH_1 or
                   D2Object.EXPANSION_CAMP_FIRE or
                   D2Object.EXPANSION_TOWN_TORCH or
                   D2Object.EXPANSION_TORCH_2 or
                   D2Object.ICE_CAVE_TORCH_1 or
                   D2Object.ICE_CAVE_TORCH_2 or
                   D2Object.EXPANSION_TIKI_TORCH or
                   D2Object.WORLDSTONE_TORCH_1 or
                   D2Object.WORLDSTONE_TORCH_2 or
                   D2Object.EXPANSION_TEMPLE_TORCH_1 or
                   D2Object.EXPANSION_TEMPLE_TORCH_2 or
                   D2Object.BLACKSMITH_FORGE or
                   D2Object.RED_BAALS_LAIR_TORCH_1 or
                   D2Object.RED_BAALS_LAIR_TORCH_2 or
                   D2Object.CANDLES_TEMPLE or
                   D2Object.ARREATS_SUMMIT_TORCH_2 or
                   D2Object.BAAL_TORCH_BIG or
                   D2Object.FIRE_PLACE_GUY => true,
                   _ => false
               };
    }
}